# Site settings
author: Telayna Wong
title: 
header-img: img/home-bg.png
email: tellenwong@gmail.com
copyright_name: Telayna Wong
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tellenwong

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
